import { initiateUploads } from '@/app/di';
import {
  InternalServerErrorResponse,
  UnauthorizedErrorResponse,
  ValidationErrorResponse,
} from '@/shared/errors';
import { checkJwt, validateRequest } from '@/shared/middlewares';
import { openapiRegistry } from '@/shared/openapi-registry';
import { requireDefined, requireDuration } from '@/shared/utils';
import type { Response, Router } from 'express';
import { z } from 'zod';

export function registerRoute(uploadsRouter: Router) {
  uploadsRouter.post(
    '/', //
    checkJwt(),
    validateRequest({ body: RequestBodySchema }),
    async (req, res: Response<z.infer<typeof ResponseSchema>>) => {
      const userId = requireDefined(req.user?.id);
      const albumId = req.body.albumId ?? null;
      const files = req.body.files.map((file) => ({
        ...file,
        ttl: file.ttl ? requireDuration(file.ttl) : null,
      }));
      const result = await initiateUploads.execute({ userId, albumId, files });
      const response = ResponseSchema.decode({ data: result });
      res.json(response);
    },
  );
}

const FileMetadataSchema = z.object({
  id: z.string().meta({
    example: 'file_1',
    description: `
A unique identifier generated by the client for this file.  
This value is echoed back in the response and should be used to match files with their upload info.  
Must be unique within the request.`,
  }),
  fileName: z
    .string()
    .regex(/^(\w|\s|-)+$/)
    .meta({ description: 'Original filename without extension', example: 'Cat' }),
  mimeType: z
    .string()
    .regex(/^(image|audio|video)\/[a-zA-Z0-9\-+]+$/)
    .meta({ example: 'image/png' }),
  sizeBytes: z.int().min(1).meta({ example: 1042 }),
  sha256Hex: z.hash('sha256', { enc: 'hex', error: 'Invalid hash, should be sha256 hex string' }),
  isPublic: z.boolean(),
  ttl: z
    .string()
    .regex(/^\d+[smhd]$/)
    .optional()
    .meta({
      example: '3d',
      description: `
The time-to-live after which the file will be automatically deleted.  
Supported units: \`s\`, \`m\`, \`h\`, \`d\` (seconds, minutes, hours and days respectively).  
Minimum period - 1 hour, maximum - 30 days.`,
    }),
});

const RequestBodySchema = z.object({
  albumId: z.uuid().optional(),
  files: z
    .array(FileMetadataSchema)
    .nonempty()
    .superRefine((items, ctx) => {
      const seenIds = new Set();
      items.forEach((item) => {
        if (seenIds.has(item.id)) {
          ctx.addIssue({ code: 'custom', message: `Id \`${item.id}\` is not unique` });
        }
        seenIds.add(item.id);
      });
    }),
});

const ResponseSchema = z
  .object({
    data: z
      .array(
        z.discriminatedUnion('status', [
          z.object({
            id: z.string().meta({ example: 'file_1' }),
            status: z
              .literal('ok')
              .meta({ description: 'A copy of file found, no upload required.' }),
          }),
          z.object({
            id: z.string().meta({ example: 'file_1' }),
            status: z.literal('upload_required'),
            url: z.url(),
            method: z.enum(['PUT']),
            headers: z.record(z.string(), z.union([z.string(), z.number()])).meta({
              example: {
                'Content-Type': 'image/png',
                'Content-Length': 1042,
                'x-amz-checksum-sha256': 'ABCDeFg6UgoA5KmX6T4Xq4hupaIIt9KQh/ZDKvNyroE=',
              },
            }),
          }),
        ]),
      )
      .nonempty(),
  })
  .brand<'Response'>();

openapiRegistry.registerPath({
  method: 'post',
  path: '/api/v1/uploads',
  summary: 'Initiate uploads',
  description: `
Receives metadata for multiple files and returns the information needed for direct uploading to a blob storage.  
For each file, the response either:
- provides the upload URL, method and headers **required** for uploading
- indicates that no upload is required.
Provide the \`albumId\` parameter to automatically link the files to the album.`,
  request: {
    headers: z.object({
      Authorization: z.templateLiteral(['Bearer ', z.jwt()]).meta({ description: 'Bearer `JWT`' }),
    }),
    body: {
      description: 'List of file metadata',
      content: { 'application/json': { schema: RequestBodySchema } },
    },
  },
  tags: ['Uploads', 'R2'],
  responses: {
    200: {
      description: 'Upload information for requested files',
      content: { 'application/json': { schema: ResponseSchema } },
    },
    ...UnauthorizedErrorResponse,
    ...ValidationErrorResponse,
    ...InternalServerErrorResponse,
  },
});
