import { checkJwt, UnauthorizedResponse, validateRequest } from '@/shared/middlewares';
import { initiateUploads } from '@/di';
import { requireDefined, requireDuration } from '@/shared/utils';
import { z } from 'zod';
import { MimeTypeSchema, Sha256Base64Schema } from '@/shared/schemas/primitives.zod';
import { openapiRegistry } from '@/shared/openapi-registry';
import { InternalServerErrorResponse, ValidationErrorResponse } from '@/shared/errors';
import type { Response, Router } from 'express';

export function registerRoute(uploadsRouter: Router) {
  uploadsRouter.post(
    '/signed-urls', //
    checkJwt(),
    validateRequest({ body: RequestBodySchema }),
    async (req, res: Response<z.infer<typeof ResponseSchema>>) => {
      const userId = requireDefined(req.user?.id);
      const albumId = req.body.albumId ?? null;
      const files = req.body.files.map((file) => ({
        ...file,
        ttl: file.ttl ? requireDuration(file.ttl) : null,
      }));
      const result = await initiateUploads.execute({ userId, albumId, files });
      const response = ResponseSchema.decode({ data: result });
      res.json(response);
    },
  );
}

const FileMetadataSchema = z.object({
  id: z.string().meta({
    example: 'file_1',
    description: `
A unique identifier generated by the client for this file.  
This value is echoed back in the response and should be used to match files with their upload info.  
Must be unique within the request.`,
  }),
  fileName: z.string().nonempty().meta({ example: 'Cat' }),
  mimeType: MimeTypeSchema,
  sizeBytes: z.int().min(1).meta({ example: 1042 }),
  sha256Base64: Sha256Base64Schema.meta({
    description: 'Should be unique for each file. Duplicates will be ignored.',
  }),
  ttl: z
    .string()
    .regex(/^\d+[smhd]$/)
    .optional()
    .meta({
      example: '3d',
      description: `
The time-to-live after which the file will be automatically deleted.  
Supported units: \`s\`, \`m\`, \`h\`, \`d\` (seconds, minutes, hours and days respectively).  
Minimum period - 1 hour, maximum - 30 days.`,
    }),
});

const RequestBodySchema = z.object({
  albumId: z.uuid().optional(),
  files: z
    .array(FileMetadataSchema)
    .nonempty()
    .superRefine((items, ctx) => {
      const seenIds = new Set();
      items.forEach((item) => {
        if (seenIds.has(item.id)) {
          ctx.addIssue({ code: 'custom', message: `Id \`${item.id}\` is not unique` });
        }
        seenIds.add(item.id);
      });
    }),
});

const ResponseSchema = z
  .object({
    data: z
      .array(
        z.discriminatedUnion('uploadNeeded', [
          z.object({ id: z.string().meta({ example: 'file_1' }), uploadNeeded: z.literal(false) }),
          z.object({
            id: z.string().meta({ example: 'file_1' }),
            uploadNeeded: z.literal(true),
            url: z.url(),
            method: z.enum(['PUT']),
            headers: z.record(z.string(), z.union([z.string(), z.number()])).meta({
              example: {
                'Content-Type': 'image/png',
                'Content-Length': 1042,
                'x-amz-checksum-sha256': 'ABCDeFg6UgoA5KmX6T4Xq4hupaIIt9KQh/ZDKvNyroE=',
              },
            }),
          }),
        ]),
      )
      .nonempty(),
  })
  .brand<'Response'>();

openapiRegistry.registerPath({
  method: 'post',
  path: '/api/v1/uploads/signed-urls',
  summary: 'Get signed URLs for R2 uploads',
  description: `
Validates file metadata and returns info for direct-to-storage uploading.
`,
  request: {
    headers: z.object({
      Authorization: z.templateLiteral(['Bearer ', z.jwt()]).meta({ description: 'Bearer `JWT`' }),
    }),
    body: {
      description: 'Files metadata',
      content: { 'application/json': { schema: RequestBodySchema } },
    },
  },
  tags: ['Uploads', 'R2'],
  responses: {
    200: {
      description: 'List of signed URLs, methods and headers **required** for uploading.',
      content: { 'application/json': { schema: ResponseSchema } },
    },
    ...UnauthorizedResponse,
    ...ValidationErrorResponse,
    ...InternalServerErrorResponse,
  },
});
