import { checkJwt, UnauthorizedResponse, validateRequest } from '@/shared/middlewares';
import { initiateUploads } from '@/di';
import { requireDefined } from '@/shared/utils';
import type { Response, Router } from 'express';
import { z } from 'zod';
import { MimeTypeSchema, Sha256Base64Schema } from '@/shared/schemas/primitives.zod';
import { openapiRegistry } from '@/shared/openapi-registry';
import { InternalServerErrorResponse, ValidationErrorResponse } from '@/shared/errors';

export function registerRoute(mediaRouter: Router) {
  mediaRouter.post(
    '/signed-urls', //
    checkJwt(),
    validateRequest({ body: RequestBodySchema }),
    async (req, res: Response<z.infer<typeof ResponseSchema>>) => {
      const userId = requireDefined(req.user?.id);
      const { collectionId = null, files } = req.body;
      const result = await initiateUploads.execute({ userId, collectionId, files });
      const response = ResponseSchema.decode({ data: result });
      res.json(response);
    },
  );
}

const FileMetadataSchema = z.object({
  id: z.string().meta({
    example: 'file_1',
    description: `A unique identifier generated by the client for this file. This value is echoed back in the response and should be used to match each file with its signed upload URL. Must be unique within the request.`,
  }),
  title: z.string().nonempty().meta({ example: 'Cat' }),
  mimeType: MimeTypeSchema,
  sizeBytes: z.int().min(1).meta({ example: 1042 }),
  sha256Base64: Sha256Base64Schema,
});

const RequestBodySchema = z.object({
  collectionId: z.uuid().optional(),
  files: z
    .array(FileMetadataSchema)
    .nonempty()
    .superRefine((items, ctx) => {
      const uniqueIds = new Set(items.map((item) => item.id));
      if (uniqueIds.size !== items.length) {
        ctx.addIssue({
          code: 'custom',
          message: 'All files must have unique IDs',
        });
      }
    }),
});

const ResponseSchema = z
  .object({
    data: z
      .array(
        z.object({
          url: z.url(),
          method: z.enum(['PUT']),
          headers: z.object({
            'Content-Type': MimeTypeSchema,
            'Content-Length': z.number().min(1).meta({ example: 1042 }),
            'x-amz-checksum-sha256': Sha256Base64Schema,
          }),
        }),
      )
      .nonempty(),
  })
  .brand<'Response'>();

openapiRegistry.registerPath({
  method: 'post',
  path: '/api/v1/media/signed-urls',
  summary: 'Get signed URLs for R2 uploads',
  description: `
Validates file metadata and returns info for direct-to-storage uploading.
`,
  request: {
    headers: z.object({
      Authorization: z.templateLiteral(['Bearer ', z.jwt()]).meta({ description: 'Bearer `JWT`' }),
    }),
    body: {
      description: 'Files metadata',
      content: { 'application/json': { schema: RequestBodySchema } },
    },
  },
  tags: ['Uploads', 'R2'],
  responses: {
    200: {
      description: 'List of signed URLs, methods and headers **required** for uploading.',
      content: { 'application/json': { schema: ResponseSchema } },
    },
    ...UnauthorizedResponse,
    ...ValidationErrorResponse,
    ...InternalServerErrorResponse,
  },
});
